source: /
paths:
  uploads: uploads
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  posts:
    path: _posts
    output: true
    icon: notes
    _inputs:
      title:
        type: auto
        label: Titel
        comment: Indlæggets titel
        cascade: true
      description:
        type: auto
        label: Beskrivelse
        comment: Kort beskrivelse af indlægget
        cascade: true
      category:
        type: auto
        label: Katgeori
        cascade: true
      podcast-id:
        type: auto
        label: Podcast ID (Kun hvis kategori er podcast)
        comment: >-
          Podcast afsnittets unikke id (Du finder det i Spodify linket til
          podcasten)
        cascade: true
      video:
        type: file
        label: Video (Kun hvis kategori er video)
        comment: Sti til videoen
        cascade: true
      subs:
        type: file
        label: Undertekster (Kun hvis kategori er video)
        comment: Sti til underteksterne
        cascade: true
      image:
        type: auto
        label: Billede
        cascade: true
      published:
        type: switch
        label: Publiceret
        cascade: true
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: /.cloudcannon/schemas/blog-post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  events:
    path: _events
    output: true
    icon: notes
    _inputs:
      title:
        type: auto
        label: Titel
        comment: Eventets titel
        cascade: true
      subtitle:
        type: auto
        label: Undetitel
        cascade: true
      image:
        type: auto
        label: Billede
        cascade: true
      date:
        type: date
        label: Dato
        cascade: true
      infomode:
        type: switch
        label: Er eventet et infomøde?
        cascade: true
      infomode-link:
        type: select
        options:
          allow_empty: true
          values: collections.educations
        label: Hvilken uddannelse er infomødet for? (Kun hvis Infomøde er slået til)
        cascade: true
      billetto:
        type: switch
        label: Kan man tilmelde sig via Billetto?
        cascade: true
      billetto-nr:
        type: auto
        label: Billetto ID (Kun hvis Billetto er slået til)
        comment: Billetto event unik ID. Du kan finde det i billettos kontrolpanel.
        cascade: true
      price:
        type: auto
        label: Pris
        cascade: true
      place:
        type: auto
        label: lokation
        cascade: true
      time:
        type: text
        label: Tid
        cascade: true
      published:
        type: switch
        label: Publiceret
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: /.cloudcannon/schemas/event.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  employees:
    path: _employees
    output: true
    icon: notes
    _inputs:
      title:
        type: auto
        label: Navn
        cascade: true
      order:
        type: number
        label: Rækkefølge
        cascade: true
      description:
        type: auto
        label: Titler/titel
        comment: Diretør, konsulent osv.
        cascade: true
      image:
        type: auto
        label: Billede
        cascade: true
      small-portrait-image:
        type: auto
        label: Billede (Lille)
        cascade: true
      call:
        type: auto
        label: Telefon nr.
        cascade: true
      meta-title:
        type: auto
        label: Titel (Metadata)
        cascade: true
      email:
        type: auto
        label: E-mailadresse
        cascade: true
      on-om-os:
        type: switch
        label: Aktiveret på "Om os" side
        cascade: true
      edu:
        type: array
        label: Uddannelser
        cascade: true
      edu[*]:
        type: text
        cascade: true
      linkedin:
        type: auto
        label: Linkedin link
        cascade: true
      redirect_from:
        type: auto
        hidden: true
        cascade: true
      published:
        type: switch
        label: Publiceret
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: /.cloudcannon/schemas/employee.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  educations:
    path: _educations
    output: true
    description: ''
    icon: notes
    _editables: {}
    _inputs:
      order:
        type: number
        label: Rækefølge
        cascade: true
      title:
        type: auto
        label: Titel
        comment: Uddannelsens titel
        cascade: true
      undertitle:
        type: auto
        label: Undertitel
        comment: Ikke oblikatorisk
        cascade: true
      meta-title:
        type: auto
        label: Titel (Metadata)
        cascade: true
      description:
        type: textarea
        label: Beskrivelse
        cascade: true
      meta-description:
        type: textarea
        label: Beskrivelse (Metadata)
        cascade: true
      aktive-hold:
        type: switch
        label: Er der aktive hold?
        cascade: true
      image:
        type: image
        label: Billede
        comment: Baggrundsbilledet i headeren
        cascade: true
      image-2:
        type: image
        label: Billede 2
        comment: >-
          Billede som ligger i anden kollonne øverst på siden under "Overblik"
          sektionen (Vises kun hvis der ikke er en video i "Overblik")
        cascade: true
      adgangskrav:
        type: html
        label: Adgangskrav
        cascade: true
      location:
        type: html
        label: Sted/lokation
        cascade: true
      contact-person:
        type: select
        options:
          allow_empty: true
          values: collections.employees
          value_key: title
        label: Kontakt person
        cascade: true
      price:
        type: html
        label: Pris
        cascade: true
      undervisere:
        type: multiselect
        options:
          empty_type: array
          values: collections.employees
        label: Undervisere
        cascade: true
      kort:
        type: auto
        label: Kort
        comment: Skal der ligge et kort under sted?
        cascade: true
      kort-kode:
        type: textarea
        label: Kort kode fra Google maps
        comment: (Kun hvis Kort er slået til)
        cascade: true
      pdf:
        type: file
        label: PDF brochure
        cascade: true
      infomode:
        type: switch
        label: Er der et kommende infomøde om kurset/uddannelsen?
        cascade: true
      kollonne-1:
        type: html
        label: Kollonne 1
        comment: Tekst i kollonne 1 i Oversigt
        cascade: true
      kollonne-2:
        type: html
        label: Kollonne 2
        comment: Tekst i kollonne 2 i Oversigt
        cascade: true
      kollonne-2-billede-hojde:
        type: select
        options:
          values: _select_data.hojder
          value_key: key
          preview:
            text:
              - key: display_name
        label: Billedhøjde
        comment: Højde på billed i kollonne 2 i Oversigt
        cascade: true
      op-kollonne-1:
        type: html
        label: Kollonne 1 (Opgybning sektion)
        comment: Tekst i kollonne 1 i Opbygning
        cascade: true
      op-kollonne-2:
        type: html
        label: Kollonne 2 (Opgybning sektion)
        comment: Tekst i kollonne 2 i Opbygning
        cascade: true
      op-kollonne-banner:
        type: html
        label: Banner (Opgybning sektion)
        comment: Tekst i banneret i Opbygning
        cascade: true
      deltagerprofil:
        type: switch
        label: Deltagerprofil beskrivelse
        comment: Skal der vises en sektion med beskrivelse af deltagerprofil?
        cascade: true
      dp-kollonne-1:
        type: html
        label: Kollonne 1 (Deltagerprofil sektion)
        comment: Tekst i kollonne 1 i Deltagerprofil
        cascade: true
      dp-kollonne-2:
        type: html
        label: Kollonne 2 (Deltagerprofil sektion)
        comment: Tekst i kollonne 2 i Deltagerprofil
        cascade: true
      anbefalinger:
        type: switch
        label: Citater/testimonials
        comment: Skal der visis nogle citater/testimonials?
        cascade: true
      vidner:
        type: array
        options:
          structures: _structures.vid
        label: Testimonials
        cascade: true
      vidner[*].navn:
        type: text
        label: Navn
        cascade: true
      vidner[*].titel:
        type: text
        label: Titel/Stilling
        cascade: true
      vidner[*].text:
        type: html
        label: Tekst
        cascade: true
      date:
        type: text
        label: Dato
        cascade: true
      dates:
        type: text
        label: Datoer
        cascade: true
      name:
        type: text
        label: Navn/beskrivelse
        cascade: true
      modules:
        type: auto
        label: Moduler/Dage
        cascade: true
      day:
        type: text
        label: Dag nr.
        cascade: true
      time:
        type: text
        label: Tid (Fra - til)
        cascade: true
      place:
        type: text
        label: Sted
        cascade: true
      aar:
        type: text
        label: År (Halvår)
        comment: F.eks. Forår 2022
        cascade: true
      nested-hold:
        type: array
        options:
          structures: _structures.aar-hold
        label: Hold (Pr. år)
        comment: Hold inddelt i år
        cascade: true
      nested-hold[*].hold:
        type: array
        options:
          structures: _structures.hold
        label: Hold
        cascade: true
      hold:
        type: array
        options:
          structures: _structures.hold
        label: Hold
        cascade: true
      hold[*].modules:
        type: array
        options:
          structures: _structures.moduler
          preview:
            text:
              - key: date
        cascade: true
      opbygning-image:
        type: auto
        label: Billede i Opbygning sektion
        cascade: true
      galleri-overblik:
        type: switch
        label: Galleri sektion
        comment: Skal der være et galleri?
        cascade: true
      galleri:
        type: array
        options:
          structures: _structures.gallery
        label: Galleri
        cascade: true
      galleri[*].text:
        type: html
        label: Tekst
        cascade: true
      galleri[*].image:
        type: image
        label: Billede
        cascade: true
      galleri[*].subtitle:
        type: text
        label: Undertitel
        cascade: true
      galleri[*].title:
        type: text
        label: Titel
        cascade: true
      redirect_from:
        type: auto
        hidden: true
        cascade: true
      published:
        type: switch
        label: Publiceret
        cascade: true
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: /.cloudcannon/schemas/education.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  coachings:
    path: _coachings
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: _pages
    output: true
    icon: notes
    _enabled_editors:
      - visual
    _inputs:
      layout:
        type: auto
        hidden: true
        cascade: true
      redirect_from:
        type: auto
        hidden: true
        cascade: true
      image:
        type: image
        label: Billede
        cascade: true
      description:
        type: html
        label: Berskrivelse
        cascade: true
      meta-description:
        type: textarea
        label: Beskrivelse (SEO)
        cascade: true
      title:
        type: text
        label: Titel
        cascade: true
      meta-title:
        type: text
        label: Beskrivelse (SEO)
        cascade: true
      text:
        type: html
        label: Tekst
        cascade: true
      permalink:
        type: auto
        hidden: true
        cascade: true
      podcast-heading:
        type: text
        label: Overskrift (Podcasts)
        cascade: true
      article-heading:
        type: text
        label: Overskrift (Blog)
        cascade: true
      video-heading:
        type: text
        label: Overskrift (Videoer)
        cascade: true
      publications-heading:
        type: text
        label: Overskrift (Udgivelser/Bøger)
        cascade: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: false
  texts:
    path: _texts
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  publications:
    path: _publications
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  landings:
    path: _landings
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  consultings:
    path: _consultings
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_select_data:
  sass:
    style: compressed
  hojder:
    - key: h-md-0
      display_name: 0%
    - key: h-md-25
      display_name: 25%
    - key: h-md-50
      display_name: 50%
    - key: h-md-75
      display_name: 75%
    - key: h-md-100
      display_name: 100%
  config:
    - _config_cc.yml
_structures:
  gallery:
    style: select
    values:
      - value:
          image:
          title:
          subtitle:
          text:
  hold:
    style: select
    values:
      - value:
          title:
          modules:
  aar-hold:
    style: select
    values:
      - value:
          aar:
          hold:
  moduler:
    style: select
    values:
      - value:
          date:
          day:
          time:
          name:
          place:
  vid:
    style: select
    values:
      - value:
          navn:
          titel:
          text:
_editables: {}
data_config: {}
timezone: Europe/Copenhagen
